### ISSUE TITLE
Clustering dendrogram y-axis off

### ISSUE THREAD

**Issue by aolney** [memphis-iis/datawhys-content-notebooks#99]
![2020-09-22_08-36](https://user-images.githubusercontent.com/4432084/93889356-b6d2d180-fcae-11ea-912b-8df85687de84.png)

**Comment by aolney** [comment]
Dale do you want to take a crack since you made the images? Perhaps it could be addressed with a caption or something instead?

**Comment by ddbowman** [comment]
Hi Andrew,
I am getting an error when I try to respond on github.  This example is from our multivariate textbook, "methods of multivariate analysis" by Rencher and Christensen.  In their dendrogram plot the axis goes from 0 to 700+ and so it makes more sense to compare the numbers directly with the distances.  I created the dendrogram using a package in R and it cut off the values between 0 and 350 which is misleading.  I wonder if you could add a comment to the effect that the graphs is for illustration only to see which groups were combined at each level.
Best,
Dale

________________________________

**Comment by aolney** [comment]
@ddbowman That would work; if regenerating the figure isn't easy, what do you think about me editing the image so the top horizontal line is at 590 (approximately marked in green below)? I think that's what the student was asking (the comment was from the online course)

![image](https://user-images.githubusercontent.com/4432084/120234626-03978080-c21e-11eb-93ab-c1b807cfc963.png)

**Comment by ddbowman** [comment]
Hi Andrew,
That sounds fine to me.   The dendrogram program I used was not very flexible.  I think a commment that the y-axis might be misleading as far as the actual distances might be appropriate as well.
Best,
Dale

________________________________

**Comment by aolney** [comment]
Or, I could change the y axis to go from 0 to 700, with 590 lining up with the original horizontal line - that seems like the best if you think it would no longer be misleading

**Comment by ddbowman** [comment]
That would be optimal, I think.
Best,
Dale

________________________________

**Comment by aolney** [comment]
Ended up implementing the spirit of this, but not with 0 and 700 axis labels, because the figure wouldn't support it.

However the new labels are consistent with the distances in the preceding tables

Closing with https://github.com/memphis-iis/datawhys-content-notebooks/commit/f5f84bedb6ded11d96130a8784e82d1e0bee8787
